// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiCSHARP.apiAluguel.Models;

#nullable disable

namespace api.Migrations.portifolioMigrations
{
    [DbContext(typeof(portifolio))]
    partial class portifolioModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("apiCSHARP.apiAluguel.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Metragem")
                        .HasColumnType("REAL");

                    b.Property<decimal>("ValorAluguel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
